# Site settings
title: Your awesome title
author: Example User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Home page
latest_post_count: 3 # Number of latest posts to show on home page

# Navigation bar
# Set the links in the navigation bar. If internal is set to true then the
# site's base URL will be prepended to the href, otherwise the href will just be
# put in the link.
nav_items:
  - internal: true
    name: Blog
    href: /blog/
  - internal: true
    name: About
    href: /about/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
exclude: [README.md]
permalink: pretty
markdown: kramdown
